/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#bb1713',
        'on-secondary-container': '#fff5e6',
        'on-tertiary-fixed-variant': '#603f33',
        'surface-dim': '#dcd9d9',
        'secondary-fixed': '#ffdea3',
        'surface-bright': '#fcf9f8',
        'on-secondary-fixed': '#261900',
        'primary-fixed-dim': '#ffb4a9',
        'on-tertiary-container': '#fff8f6',
        'primary-fixed': '#ffdad5',
        'inverse-primary': '#ffb4a9',
        'on-error': '#ffffff',
        'surface-container-high': '#eae7e7',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-background': '#1b1c1c',
        'inverse-surface': '#303030',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#5d4200',
        'surface-variant': '#e5e2e1',
        'on-surface-variant': '#5c403c',
        'on-tertiary-fixed': '#2e150b',
        'tertiary-container': '#906a5c',
        'on-secondary': '#ffffff',
        'on-surface': '#1b1c1c',
        'surface-container-low': '#f6f3f2',
        tertiary: '#755245',
        outline: '#906f6b',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e5e2e1',
        'primary-container': '#d93025',
        secondary: '#7a5900',
        'surface-container': '#f0eded',
        surface: '#fcf9f8',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#410001',
        background: '#fcf9f8',
        'tertiary-fixed-dim': '#ebbcac',
        'on-primary-fixed-variant': '#930004',
        'secondary-fixed-dim': '#e08a34',
        'on-primary-container': '#fff8f7',
        'inverse-on-surface': '#f3f0ef',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#9c6a1f',
        'tertiary-fixed': '#ffdbcf',
        'outline-variant': '#e5beb8',
        primary: '#b5110e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '24px',
        lg: '48px',
        gutter: '24px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        sm: '12px',
        base: '8px',
        xs: '4px',
        xl: '80px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['"Playfair Display"', 'serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['"Playfair Display"', 'serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'display-lg': ['"Playfair Display"', 'serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
