// Central product catalog. `category` drives all sections/search/filters.
// Adding a new category later (mutton, fish, eggs, seafood, vegetables)
// requires NO structural changes — just push items with that category.

export const products = [
  // ---------------- MASALAS ----------------
  {
    id: 'garam-masala',
    name: 'Garam Masala',
    category: 'masala',
    description: 'A warm, aromatic blend of roasted whole spices ground fresh.',
    price: 180,
    rating: 4.9,
    reviews: 120,
    stock: 42,
    weight: '200g',
    freshness: null,
    tag: null,
    isNew: false,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAgePLeOE78jHcpsjZ8Qgc4UYgkxrBFTTMkbuC5LS1WP89wjFLNoWBe--qR_BbdYbN3JtnugCvafkHikESoUFsCOhtX7n-ajecaNowOFytFZ0-AA6pq1BEQpWlE1jdkPpg9GELnXL3L7P6--y8LmZljW8A8FWmkk-G40khBF5_iN9loaXelZiHezYePoSFXEXjaNexcndN75cDIFx2jermGplqVF41_ToyWK-UAtHhCe53Ir2m8syespw',
  },
  {
    id: 'biryani-masala',
    name: 'Biryani Masala',
    category: 'masala',
    description: 'Signature blend for the perfect pot of fragrant biryani.',
    price: 220,
    rating: 4.8,
    reviews: 85,
    stock: 35,
    weight: '150g',
    freshness: null,
    tag: null,
    isNew: false,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAkquy8TBle66sNWmMNdwj9PABpFCMURW6im9XsnjSCpFADcPsA-QIB8-B1N2eLwoNH9aku-BDKx00TUcTuP3LFFOl-gep-3PmHMfzNSfzj83f-PJ7B1hAUOQQqCD6piYWMrMDSghiW4CozhQ_9VpHQADasXOs3i9DYAC6KWxuGrCnIQZIgG3sHYaboBFdYmUzLfl4oPxb2s5cw2sZKSG01g7N_TZXai9P2PFnsZj3kswLz1sks4mFBUA',
  },
  {
    id: 'curry-powder',
    name: 'Curry Powder',
    category: 'masala',
    description: 'A versatile everyday curry blend for all your gravies.',
    price: 150,
    rating: 5.0,
    reviews: 42,
    stock: 60,
    weight: '200g',
    freshness: null,
    tag: null,
    isNew: false,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA7p-oFxdhI-eyNvsc30CCXQP9Lml4yfIdw0GDFoVuB8Q5e1z_kkEOINasMjjP-V9fz7SGq9wLTLRffPYDrUzovv9urbJmpmweFMG57mzSDds9fm8b96VX0pDDeN8_rlDRtgwspFVTjeYgZJD4bvw7iSKDPKqKTur75eZs4uYmFe8CQfyAtuc9V9H7ZxeUipLoSkQn1N_DWtvTscWqhF4SfzGb-PlArFB2mCknTW6m5Zq8IqNzLzP6h3Q',
  },
  {
    id: 'chole-masala',
    name: 'Chole Masala',
    category: 'masala',
    description: 'Punjabi-style spice mix for rich, tangy chole.',
    price: 170,
    rating: 4.7,
    reviews: 64,
    stock: 30,
    weight: '200g',
    freshness: null,
    tag: null,
    isNew: false,
    image: 'https://images.unsplash.com/photo-1623569559000-c3031217d717?w=400&h=400&fit=crop',
  },
  {
    id: 'sambar-masala',
    name: 'Sambar Masala',
    category: 'masala',
    description: 'South Indian classic for authentic sambar every time.',
    price: 160,
    rating: 4.8,
    reviews: 98,
    stock: 50,
    weight: '200g',
    freshness: null,
    tag: null,
    isNew: false,
    image: 'https://images.unsplash.com/photo-1633881614907-8587c9b93c2f?w=400&h=400&fit=crop',
  },
  {
    id: 'rasam-powder',
    name: 'Rasam Powder',
    category: 'masala',
    description: 'Tangy, peppery blend for comforting South Indian rasam.',
    price: 140,
    rating: 4.6,
    reviews: 53,
    stock: 48,
    weight: '150g',
    freshness: null,
    tag: null,
    isNew: false,
    image: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=400&h=400&fit=crop',
  },
  {
    id: 'chaat-masala',
    name: 'Chaat Masala',
    category: 'masala',
    description: 'Tangy street-food spice for chaats, fruits and snacks.',
    price: 120,
    rating: 4.9,
    reviews: 110,
    stock: 70,
    weight: '100g',
    freshness: null,
    tag: null,
    isNew: false,
    image: 'https://images.unsplash.com/photo-1566824099147-bef027d3a333?w=400&h=400&fit=crop',
  },
  {
    id: 'pav-bhaji-masala',
    name: 'Pav Bhaji Masala',
    category: 'masala',
    description: 'Bold Mumbai street-style blend for classic pav bhaji.',
    price: 150,
    rating: 4.7,
    reviews: 76,
    stock: 40,
    weight: '200g',
    freshness: null,
    tag: null,
    isNew: false,
    image: 'https://images.unsplash.com/photo-1543376798-62217a8d85cc?w=400&h=400&fit=crop',
  },
  {
    id: 'tandoori-masala',
    name: 'Tandoori Masala',
    category: 'masala',
    description: 'Smoky, vibrant blend for tandoori grills and marinades.',
    price: 200,
    rating: 4.8,
    reviews: 89,
    stock: 38,
    weight: '150g',
    freshness: null,
    tag: null,
    isNew: false,
    image: 'https://images.unsplash.com/photo-1547332226-395d746d139a?w=400&h=400&fit=crop',
  },
  {
    id: 'kitchen-king-masala',
    name: 'Kitchen King Masala',
    category: 'masala',
    description: 'All-purpose royal blend for everyday vegetable dishes.',
    price: 180,
    rating: 4.6,
    reviews: 47,
    stock: 44,
    weight: '200g',
    freshness: null,
    tag: null,
    isNew: false,
    image: 'https://images.unsplash.com/photo-1615485500834-bc10199bc727?w=400&h=400&fit=crop',
  },
  {
    id: 'chicken-masala',
    name: 'Chicken Masala',
    category: 'masala',
    description: 'Rich, robust blend crafted specifically for chicken curries.',
    price: 210,
    rating: 4.9,
    reviews: 132,
    stock: 55,
    weight: '200g',
    freshness: null,
    tag: null,
    isNew: false,
    image: 'https://images.unsplash.com/photo-1490026220125-b42f3d66abd6?w=400&h=400&fit=crop',
  },
  {
    id: 'mutton-masala',
    name: 'Mutton Masala',
    category: 'masala',
    description: 'Deep, earthy blend built for slow-cooked mutton curries.',
    price: 230,
    rating: 4.8,
    reviews: 91,
    stock: 28,
    weight: '200g',
    freshness: null,
    tag: null,
    isNew: false,
    image: 'https://images.unsplash.com/photo-1603122612817-2fe0e0631a93?w=400&h=400&fit=crop',
  },

  // ---------------- NEW ARRIVALS (masala) ----------------
  {
    id: 'smoked-paprika',
    name: 'Smoked Paprika',
    category: 'masala',
    description: 'Deep smoky pepper, slow-dried over oak for bold flavor.',
    price: 280,
    rating: 4.7,
    reviews: 31,
    stock: 25,
    weight: '100g',
    freshness: null,
    tag: 'SMOKY',
    isNew: true,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCyJpnwr0TQvSv85Jf8zq7KE4-b8EhZ9PSjREzkcr_71ZP2dp8Y-VVG3FP2YdCUQm_4mu7NQw9YPxHsuMWrO1uXdUVJuKeGExipv8tX88CH4R_xR7ia1g9M0CgTe_zX6ipsB50Qu8DCGus6F4TfI65VtD5IMVzvoaOijyJUEPpI5xf56h8aaZdHYE7oeZNg5pMPmxbCi8-mAwy6KDKBDKU7CHKD8-mF2OonteZGFxz26GG2Gz4QMlT0fQ',
  },
  {
    id: 'green-cardamom',
    name: 'Green Cardamom',
    category: 'masala',
    description: 'Fragrant whole cardamom pods, hand-picked for aroma.',
    price: 450,
    rating: 4.9,
    reviews: 18,
    stock: 20,
    weight: '50g',
    freshness: null,
    tag: 'AROMATIC',
    isNew: true,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuALiEcZ24SsxUm92mJyMn_Q_wqbjfzcJJF1MHa5WZUzEAb5SrbVLI8sOm2ma9Kved97_c856u9h0fRN2sGIyqDmdnbYJDlFsraO730wHmYN926_g7zi8tbkOIYepcFeD_qqcywijKTNNfXHnTpyat-ruv0iKl_of2qTrtm2X4xNgV5shOGRFKSp0n45xee_AarPqNpWgrWcaNJboQSk4ApysKN5eQFp4kz2U_JhgRX65qmZFJQdQ5jVVw',
  },
  {
    id: 'kashmiri-chili',
    name: 'Kashmiri Chili',
    category: 'masala',
    description: 'Vibrant red chili powder, mild heat with deep color.',
    price: 190,
    rating: 4.6,
    reviews: 27,
    stock: 33,
    weight: '150g',
    freshness: null,
    tag: 'PIQUANT',
    isNew: false,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB3820S8WdeOHGloG50tzNiRbNZYJDp7mIKa5u3tzxU9jyuXXGn6c7IkHdJl2kwdvG1pMyR4ZYxh7Ojj3LEyjwloyx8OKCQvEcEeo7mjaHjG1f--e89ucfEq_ERjn04-KcoyW_U_N1Up6ABfjvZMXFquYee0JHxnCRmcB8IXVcP1ZwAE-aU5zZ7EwxTi1bEu0E-J4tCY0xmGABFLiVT-VEMiwXPYCKxXuQwpg9Sjohdy2IjQB0ZMNGiig',
  },
  {
    id: 'star-anise',
    name: 'Star Anise',
    category: 'masala',
    description: 'Sweet, licorice-like whole spice pods for biryanis and stocks.',
    price: 130,
    rating: 4.8,
    reviews: 22,
    stock: 27,
    weight: '50g',
    freshness: null,
    tag: 'SWEET',
    isNew: false,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDyw7H2glSq--5QK-GVaEa8Mt9CsmunpmGFnOh5MNxfyrYtZJL_tHpWS8yOLuWLRlN3oqarvpsUZWP_xREnX-XF4NGmIOnaQvVXTiJ81Vqh5m9dR0dghMDS5iB5ClRcjr1g0HB-Fbifn9TDjbu_94Dp6Zb5i4Te9XTlzp5lTons6e_QHIgWAdYrt20Q9TkghYxN9frB3hCLW2dNc5s2-J5In27XGPJIdUT92jLa2Xjw4u_syFyJlsp4Cw',
  },

  // ---------------- FRESH CHICKEN ----------------
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    category: 'chicken',
    description: 'Skinless, boneless breast fillets. Farm fresh, cleaned daily.',
    fullDescription:
      'Skinless, boneless chicken breast fillets, hand-trimmed and cleaned the same morning they\'re packed. Lean and versatile — ideal for grilling, curries, or shredding for salads.',
    nutrition: { calories: 165, protein: 31, fat: 3.6, carbs: 0 },
    price: 320,
    rating: 4.7,
    reviews: 58,
    stock: 22,
    weight: '500g',
    freshness: 'Fresh Today',
    tag: null,
    isNew: false,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGM94s-xRjhfl3rfo1Kn_SNnCoO9jK8zbkPS1jtXri8hXHOmS50oxK3pg7B9QKTRvusyFj2MtXMUuJVAhUvQjtzmJSCc8sJUbVs997xJGTuTSRSNiIxkC50eveACViWCnku_bv5xugwXkj2ZyEFH3p2E7X1hOLyasKZk03dbY7_u-tLKbI5GsYAxRc-Rj17LaTkzNIWVHNe_x8rd2c8j_UoT9I9VMeqygoYM0FbccZT-ypE97Ywleaug',
  },
  {
    id: 'chicken-curry-cut',
    name: 'Chicken Curry Cut',
    category: 'chicken',
    description: 'Classic bone-in curry cut, ideal for everyday gravies.',
    fullDescription:
      'Bone-in curry cut pieces, cut fresh daily for maximum flavor in slow-cooked gravies. The bone-in cut adds richness that boneless cuts can\'t match — a staple for everyday home-style curries.',
    nutrition: { calories: 215, protein: 27, fat: 11, carbs: 0 },
    price: 260,
    rating: 4.8,
    reviews: 74,
    stock: 30,
    weight: '500g',
    freshness: 'Fresh Today',
    tag: null,
    isNew: false,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQYr3PGtVmYqBN_G5lOyEWRWHVG8BQ-ugEoIFhABMYbxvKmyQ6UMLHCc28CykeHxmk4aJ4IQiOVlC5NN2uyt176S2WEAUxtycTz84KhzaMV96jZqT1GYQDTtzRomaCzUMGSFp0PozK_EHt9lYtRgRGRilcViuqk9lSBWYgaXzDROerLrmfdP3JLsCmcVy-gQ7h9j-WVhZnbyWq-GsMD5qWoR6F5rNV7mRqbxihh8emZDS9Wy3kRNE-Fw',
  },
  {
    id: 'chicken-drumsticks',
    name: 'Chicken Drumsticks',
    category: 'chicken',
    description: 'Juicy drumsticks, perfect for grilling and frying.',
    fullDescription:
      'Plump, juicy drumsticks that hold up beautifully to high heat — grill, fry, or roast them whole. A favorite for weekend cookouts and kids\' plates alike.',
    nutrition: { calories: 172, protein: 24, fat: 8, carbs: 0 },
    price: 280,
    rating: 4.9,
    reviews: 63,
    stock: 26,
    weight: '500g',
    freshness: 'Fresh Today',
    tag: null,
    isNew: false,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-2ByAwrQBAeXtKcXVpLG41ysPj3IovCix6VLwUzd9zoU9olaWT3h0HGpgCCyQAosRW8Cbb0faEKW4NDcD5_d2zrWACR9d-A8q94Z925ESzbyVZ0hkfAibXFjnSYyjrVZgwQb7zmhN1BPrf38Fe0db1cWJpqTxgZ_foyAhi1EtXgNdF6FLpZMzAme5eSuIt88Uz5fnlCRGJeFCoCUldpfoSXZSXn0SocYfLGcpeZoLS461wCMrE_RjDA',
  },
  {
    id: 'chicken-mince',
    name: 'Chicken Mince (Keema)',
    category: 'chicken',
    description: 'Freshly ground chicken mince, perfect for keema and kebabs.',
    fullDescription:
      'Freshly ground on-site from lean cuts, with no fillers added. Perfect for keema, kebabs, cutlets, or a quick weeknight bolognese.',
    nutrition: { calories: 190, protein: 26, fat: 9, carbs: 0 },
    price: 300,
    rating: 4.6,
    reviews: 39,
    stock: 18,
    weight: '500g',
    freshness: 'Fresh Today',
    tag: null,
    isNew: false,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQYr3PGtVmYqBN_G5lOyEWRWHVG8BQ-ugEoIFhABMYbxvKmyQ6UMLHCc28CykeHxmk4aJ4IQiOVlC5NN2uyt176S2WEAUxtycTz84KhzaMV96jZqT1GYQDTtzRomaCzUMGSFp0PozK_EHt9lYtRgRGRilcViuqk9lSBWYgaXzDROerLrmfdP3JLsCmcVy-gQ7h9j-WVhZnbyWq-GsMD5qWoR6F5rNV7mRqbxihh8emZDS9Wy3kRNE-Fw',
  },
  {
    id: 'chicken-wings',
    name: 'Chicken Wings',
    category: 'chicken',
    description: 'Plump, tender wings ready for your favorite marinade.',
    fullDescription:
      'Plump, tender wings, split and cleaned, ready for your favorite marinade. Great for tandoori, buffalo-style, or a simple pepper-garlic toss.',
    nutrition: { calories: 203, protein: 18, fat: 14, carbs: 0 },
    price: 240,
    rating: 4.8,
    reviews: 51,
    stock: 24,
    weight: '500g',
    freshness: 'Fresh Today',
    tag: null,
    isNew: false,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-2ByAwrQBAeXtKcXVpLG41ysPj3IovCix6VLwUzd9zoU9olaWT3h0HGpgCCyQAosRW8Cbb0faEKW4NDcD5_d2zrWACR9d-A8q94Z925ESzbyVZ0hkfAibXFjnSYyjrVZgwQb7zmhN1BPrf38Fe0db1cWJpqTxgZ_foyAhi1EtXgNdF6FLpZMzAme5eSuIt88Uz5fnlCRGJeFCoCUldpfoSXZSXn0SocYfLGcpeZoLS461wCMrE_RjDA',
  },
  {
    id: 'chicken-boneless',
    name: 'Boneless Chicken',
    category: 'chicken',
    description: 'Cleanly deboned chicken cubes, ready to cook.',
    fullDescription:
      'Cleanly deboned chicken, cut into even cubes so it cooks through fast and evenly. Ideal for curries, stir-fries, and kebabs — no bones to work around.',
    nutrition: { calories: 172, protein: 25, fat: 7, carbs: 0 },
    price: 340,
    rating: 4.8,
    reviews: 47,
    stock: 20,
    weight: '500g',
    freshness: 'Fresh Today',
    tag: null,
    isNew: false,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGM94s-xRjhfl3rfo1Kn_SNnCoO9jK8zbkPS1jtXri8hXHOmS50oxK3pg7B9QKTRvusyFj2MtXMUuJVAhUvQjtzmJSCc8sJUbVs997xJGTuTSRSNiIxkC50eveACViWCnku_bv5xugwXkj2ZyEFH3p2E7X1hOLyasKZk03dbY7_u-tLKbI5GsYAxRc-Rj17LaTkzNIWVHNe_x8rd2c8j_UoT9I9VMeqygoYM0FbccZT-ypE97Ywleaug',
  },
  {
    id: 'chicken-whole',
    name: 'Whole Chicken (Skinless)',
    category: 'chicken',
    description: 'Farm-raised whole chicken, cleaned and skinned fresh.',
    fullDescription:
      'A whole farm-raised bird, skinned and cleaned fresh the same day. Roast it whole, spatchcock it for the grill, or have it cut to order at the counter.',
    nutrition: { calories: 165, protein: 27, fat: 5.5, carbs: 0 },
    price: 380,
    rating: 4.9,
    reviews: 44,
    stock: 15,
    weight: '1kg',
    freshness: 'Fresh Today',
    tag: null,
    isNew: false,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQYr3PGtVmYqBN_G5lOyEWRWHVG8BQ-ugEoIFhABMYbxvKmyQ6UMLHCc28CykeHxmk4aJ4IQiOVlC5NN2uyt176S2WEAUxtycTz84KhzaMV96jZqT1GYQDTtzRomaCzUMGSFp0PozK_EHt9lYtRgRGRilcViuqk9lSBWYgaXzDROerLrmfdP3JLsCmcVy-gQ7h9j-WVhZnbyWq-GsMD5qWoR6F5rNV7mRqbxihh8emZDS9Wy3kRNE-Fw',
  },

  // ---------------- TODAY'S COMBOS ----------------
  {
    id: 'chicken-curry-kit',
    name: 'Chicken Curry Kit',
    category: 'combo',
    description: 'Everything you need for a perfect chicken curry, in one kit.',
    price: 420,
    rating: 4.9,
    reviews: 29,
    stock: 20,
    weight: 'Combo',
    freshness: 'Fresh Today',
    tag: 'COMBO',
    isNew: false,
    includes: ['Chicken Curry Cut (500g)', 'Garam Masala', 'Turmeric Powder', 'Chilli Powder'],
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=400&fit=crop',
  },
  {
    id: 'biryani-kit',
    name: 'Biryani Kit',
    category: 'combo',
    description: 'Restaurant-style biryani, made simple with this all-in-one kit.',
    price: 480,
    rating: 5.0,
    reviews: 34,
    stock: 16,
    weight: 'Combo',
    freshness: 'Fresh Today',
    tag: 'COMBO',
    isNew: false,
    includes: ['Chicken Curry Cut (500g)', 'Biryani Masala', 'Bay Leaf', 'Cardamom'],
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=400&fit=crop',
  },
]

// Convenience selectors — keep old import names working so existing
// components (PopularBlends/NewArrivals) don't need prop-shape changes.
export const popularBlends = products.filter((p) => p.category === 'masala' && !p.isNew)
export const newArrivals = products.filter((p) => p.isNew)
export const chickenProducts = products.filter((p) => p.category === 'chicken')
export const comboProducts = products.filter((p) => p.category === 'combo')

// Frozen/packed & expiry info shown on product cards. Chicken is fresh-cut
// with a short shelf life; masala blends are shelf-stable for months.
export function getFreshnessInfo(item) {
  const today = new Date()
  const fmt = (d) => d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })

  if (item.category === 'chicken') {
    const expiry = new Date(today.getTime() + 2 * 24 * 60 * 60 * 1000)
    return {
      packedOn: fmt(today),
      expiryOn: fmt(expiry),
      shelfLife: 'Use within 2 days, refrigerated',
    }
  }

  const expiry = new Date(today.getTime() + 365 * 24 * 60 * 60 * 1000)
  return {
    packedOn: fmt(today),
    expiryOn: expiry.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }),
    shelfLife: 'Best within 12 months, cool & dry place',
  }
}

export const categories = [
  { id: 'masala', label: 'Masalas', icon: '🌶️', sectionId: 'masalas-section' },
  { id: 'chicken', label: 'Fresh Chicken', icon: '🍗', sectionId: 'chicken-section' },
]

// Simple multi-field search across the whole catalog.
export function searchProducts(query) {
  const q = query.trim().toLowerCase()
  if (!q) return []
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      (p.description && p.description.toLowerCase().includes(q))
  )
}
